namespace BlazorDatasheet.Formula.Core.Interpreter.Lexing;

public enum Tag
{
    Eof,
    Number,
    BadToken,
    GreaterThanOrEqualToToken,
    LessThanOrEqualToToken,
    StringToken,
    ListSeparatorToken,
    PlusToken,
    StarToken,
    MinusToken,
    SlashToken,
    EqualsToken,
    IdentifierToken,
    NotEqualToToken,
    GreaterThanToken,
    RowSeparatorToken,
    BangToken,
    PercentToken,
    LessThanToken,
    LeftParenthToken,
    RightParenthToken,
    LeftCurlyBracketToken,
    RightCurlyBracketToken,
    AmpersandToken,
    ColonToken,
    AddressToken,
    LogicalToken,
    Whitespace,
    SheetLocatorToken,
    ErrorToken
}